### ISSUE TITLE
missing training script

### ISSUE THREAD

**Issue by fzari** [xupei0610/AdaptNet#1]
Hi,

The training script for AdaptNet is not provided. And it seems that the training script provided for the Composite model does not work with AdaptNet, which leads to several issues when trying to run it for AdaptNet. 

Please clarify if there are specific steps or configurations to follow for training AdaptNet, or provide a new script to streamline the process.

**Comment by xupei0610** [comment]
After wrapping the pre-trained policy network using `AdaptNet` in `models.py`, it should be able to perform training in a normal policy training approach. We recommend our new work at https://github.com/xupei0610/guitar for an example using AdaptNet during training.
