### ISSUE TITLE
 How to transfer the data from LAFAN1 to the json or pkl file? 

### ISSUE THREAD

**Issue by motor-x** [xupei0610/AdaptNet#2]
Hi,

I am very interesting this excellent work. Could you please let me know how to transfer the data from LAFAN1 to the [json](https://github.com/xupei0610/CompositeMotion/blob/main/assets/motions/locomotion/lafan1_run1_subject5_160_2105_mirror.json) or [pkl](https://github.com/xupei0610/CompositeMotion/blob/main/assets/motions_binary/locomotion/crouch_lafan1_walk3_subject5_2490_2735_mirror.pkl) file?

Thank you!

**Comment by xupei0610** [comment]
Ref xupei0610/CompositeMotion#1
